### Obtener todos los usuarios
GET http://localhost:8080/api/v3/usuarios
Accept: application/json

### ---

### Obtener un usuario por ID
GET http://localhost:8080/api/v3/usuarios/1
Accept: application/json

### ---

### Crear un nuevo usuario (depende de una sucursal existente, ej. id_sucursal: 1)
POST http://localhost:8080/api/v3/usuarios
Content-Type: application/json

{
  "idSucursal": 1,
  "nombre": "Andres Leonardo",
  "username": "andres",
  "passwordHash": "123123",
  "email": "andreslgp@empresa.com",
  "estado": true,
  "rol": "ADMIN"
}